name: fatoortk
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - asset/image/

  fonts:
    - family: Oxanium
      fonts:
        - asset: asset/font/Oxanium-VariableFont_wght.ttf
    - family: Cairo
      fonts:
        - asset: asset/font/Cairo-VariableFont_slnt,wght.ttf
    - family: Inter
      fonts:
        - asset: asset/font/Inter-Italic-VariableFont_opsz,wght.ttf
        - asset: asset/font/Inter-VariableFont_opsz,wght.ttf
      
