platform :ios, '12.0'

install! 'cocoapods', :disable_input_output_paths => true

# تأكد أن المسار صحيح حسب موقع مجلد flutter لديك
require File.expand_path(File.join("C:/flutter/packages/flutter_tools/bin/podhelper.rb"), __dir__)


target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))

  # Firebase Pods
  pod 'Firebase/Core', '~> 8.11.0'
  pod 'Firebase/Auth', '~> 8.11.0'

end
