platform :ios, '12.0'

 # تعطيل مسارات الإدخال والإخراج
 install! 'cocoapods', :disable_input_output_paths => true
 require File.expand_path('./podhelper.rb', __dir__)






 


target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_root = File.expand_path('..', __dir__)

  # تضمين مكتبة Flutter يدويًا
  pod 'Flutter', :path => "#{flutter_root}/flutter/bin/cache/artifacts/engine/ios"

  # إضافة جميع الـ Pods التي تحتاجها
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

 

  # يجب أن يكون `flutter_install_all_ios_pods` في النهاية
  flutter_install_all_ios_pods(flutter_root)
end
